### Create a New URL
POST http://localhost:8000/api/create_short_url/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1MzQ3NDc2LCJpYXQiOjE3MjUzNDM4NzYsImp0aSI6Ijg1Y2UyOTIxMmMzMjRlN2FhMzk2ZDJlYmU3NTI3MDllIiwidXNlcl9pZCI6MX0.elXy8hwLVzxzXSS4pfEJj8-_utYJ-WuYU_bQI-YIo48

{
  "long_url": "www.google.com",
  "validity_period": "2024-09-30T23:59:59Z",
  "is_active": true,
  "one_time_only": true,
  "password": ""
}

### Give Long URL
POST http://localhost:8000/api/get_long_url/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1Mjc3NzIyLCJpYXQiOjE3MjUyNzQxMjIsImp0aSI6IjYzMWFiN2I4MDliZjQwNzc5NGZlNzM1YWE1OWM5NTM0IiwidXNlcl9pZCI6MX0.e7TrqqN-0swanxY2nPpSGBB5nC2RlXN1syWqywchrgI

{
  "short_url": "RTfq0F",
  "password": ""
}

### Update URL Activity
PUT http://localhost:8000/api/update_activity/sDZlCQ/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1Mjc3NzIyLCJpYXQiOjE3MjUyNzQxMjIsImp0aSI6IjYzMWFiN2I4MDliZjQwNzc5NGZlNzM1YWE1OWM5NTM0IiwidXNlcl9pZCI6MX0.e7TrqqN-0swanxY2nPpSGBB5nC2RlXN1syWqywchrgI

{
  "is_active": true
}

### Update URL Validity Period
PUT http://localhost:8000/api/update_validity/sDZlCQ/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1Mjc3NzIyLCJpYXQiOjE3MjUyNzQxMjIsImp0aSI6IjYzMWFiN2I4MDliZjQwNzc5NGZlNzM1YWE1OWM5NTM0IiwidXNlcl9pZCI6MX0.e7TrqqN-0swanxY2nPpSGBB5nC2RlXN1syWqywchrgI

{
  "validity_period": "2024-09-03T12:00:00Z"
}

### List All URLs
GET http://localhost:8000/api/urls/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1Mjc3NzIyLCJpYXQiOjE3MjUyNzQxMjIsImp0aSI6IjYzMWFiN2I4MDliZjQwNzc5NGZlNzM1YWE1OWM5NTM0IiwidXNlcl9pZCI6MX0.e7TrqqN-0swanxY2nPpSGBB5nC2RlXN1syWqywchrgI