### Create a New URL
POST http://localhost:8000/api/create_short_url/
Content-Type: application/json

{
  "long_url": "https://www.google.com",
  "validity_period": "2024-09-30T23:59:59Z",
  "created_by": 1,
  "is_active": true,
  "one_time_only": false,
  "password": ""
}

### Give Long URL
POST http://localhost:8000/api/get_long_url/
Content-Type: application/json

{
  "short_url": "MUI348",
  "password": "123"
}

### Update URL Activity
PUT http://localhost:8000/api/update_activity/D4Q2Wm/
Content-Type: application/json

{
  "is_active": true
}

### Update URL Validity Period
PUT http://localhost:8000/api/update_validity/D4Q2Wm/
Content-Type: application/json

{
  "validity_period": "2024-09-01T12:00:00Z"
}

### List All URLs
GET http://localhost:8000/api/urls/
Accept: application/json

