### Create a New URL
POST http://167.71.39.190:8000/api/create_short_url/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1ODY3NTMzLCJpYXQiOjE3MjU4NjM5MzMsImp0aSI6Ijk3MThiYTllZGYwNDRlNjVhM2M4YjFlNmQ1YzNlZDA1IiwidXNlcl9pZCI6MX0.BIxdOiYFqMaKSuA9U40xYofEHtDk4SFrmfXgLHxpvXc

{
  "long_url": "http://www.google.com",
  "validity_period": "2024-09-30T23:59:59Z",
  "is_active": true,
  "one_time_only": true,
  "password": "123"
}

### Give Long URL
POST http://167.71.39.190:8000/api/get_long_url/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1Mjc3NzIyLCJpYXQiOjE3MjUyNzQxMjIsImp0aSI6IjYzMWFiN2I4MDliZjQwNzc5NGZlNzM1YWE1OWM5NTM0IiwidXNlcl9pZCI6MX0.e7TrqqN-0swanxY2nPpSGBB5nC2RlXN1syWqywchrgI

{
  "short_url": "RTfq0F",
  "password": ""
}

### Update URL Activity
PUT http://167.71.39.190:8000/api/update_activity/sDZlCQ/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1Mjc3NzIyLCJpYXQiOjE3MjUyNzQxMjIsImp0aSI6IjYzMWFiN2I4MDliZjQwNzc5NGZlNzM1YWE1OWM5NTM0IiwidXNlcl9pZCI6MX0.e7TrqqN-0swanxY2nPpSGBB5nC2RlXN1syWqywchrgI

{
  "is_active": true
}

### Update URL Validity Period
PUT http://167.71.39.190:8000/api/update_validity/sDZlCQ/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1Mjc3NzIyLCJpYXQiOjE3MjUyNzQxMjIsImp0aSI6IjYzMWFiN2I4MDliZjQwNzc5NGZlNzM1YWE1OWM5NTM0IiwidXNlcl9pZCI6MX0.e7TrqqN-0swanxY2nPpSGBB5nC2RlXN1syWqywchrgI

{
  "validity_period": "2024-09-03T12:00:00Z"
}

### Delete URL
PUT http://167.71.39.190:8000/api/delete/Gzf9OP/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1ODY3NTMzLCJpYXQiOjE3MjU4NjM5MzMsImp0aSI6Ijk3MThiYTllZGYwNDRlNjVhM2M4YjFlNmQ1YzNlZDA1IiwidXNlcl9pZCI6MX0.BIxdOiYFqMaKSuA9U40xYofEHtDk4SFrmfXgLHxpvXc

{
  "is_deleted": true
}

### List All URLs
GET http://167.71.39.190:8000/api/urls/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1Mjc3NzIyLCJpYXQiOjE3MjUyNzQxMjIsImp0aSI6IjYzMWFiN2I4MDliZjQwNzc5NGZlNzM1YWE1OWM5NTM0IiwidXNlcl9pZCI6MX0.e7TrqqN-0swanxY2nPpSGBB5nC2RlXN1syWqywchrgI


