# Generated by Django 5.1 on 2024-08-28 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
