# Generated by Django 5.1 on 2024-09-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
