# Generated by Django 5.1 on 2024-09-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicknote',
            name='text',
            field=models.BinaryField(),
        ),
    ]
