# Generated by Django 5.1 on 2024-09-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_alter_quicknote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicknote',
            name='text',
            field=models.TextField(),
        ),
    ]
