# Generated by Django 5.1 on 2024-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_alter_quicknote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='long_url',
            field=models.URLField(max_length=2048),
        ),
    ]
