# Generated by Django 5.0.8 on 2024-09-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0012_pdffile_qrcode_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDFFile',
            new_name='PDF',
        ),
    ]
