# Generated by Django 5.0.8 on 2024-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0013_rename_pdffile_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknote',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
