# Generated by Django 5.0.8 on 2024-09-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0014_quicknote_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quicknote',
            name='file',
        ),
        migrations.AlterField(
            model_name='quicknote',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicknote',
            name='files',
            field=models.ManyToManyField(blank=True, to='utility.file'),
        ),
    ]
