# Generated by Django 5.0.8 on 2024-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0015_file_remove_quicknote_file_alter_quicknote_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicknote',
            name='files',
        ),
        migrations.AddField(
            model_name='quicknote',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
